options:
  volume-backend-name:
    type: string
    default:
    description: |
      Volume backend name for the backend. The default value is the
      application name in the Juju model.
  use-multipath:
    type: boolean
    default: True
    description: |
      Whether to use a multipath connection for iSCSI or FC in Cinder
      volume service. Enabling multipath for VMs is managed by the
      "use-multipath" option in the nova-compute charm.
  protocol:
    type: string
    default:
    description: |
      SAN protocol to use. Choose between iSCSI or FC.
  san-ip:
    type: string
    default:
    description: |
      PowerStore REST IP.
  san-login:
    type: string
    default:
    description: |
      PowerStore REST username.
  san-password:
    type: string
    default:
    description: |
      PowerStore REST password.
  powerstore-ports:
    type: string
    default:
    description: |
      Allowed ports. Comma separated list of PowerStore iSCSI IPs or FC
      WWNs to be used. If option is not set all ports are allowed.
